### ISSUE TITLE
Improve the configuration module

### ISSUE THREAD

**Issue by etiennenoel** [ima-tech/pristine-ts#3]
The Configuration Module is not straightforward enough. We need to know:

- If a configuration key is not provided to the kernel while it should
- If a configuration key is provided to the kernel but no module define it

We could use an object with decorators to define the "schema" and use that to know what the configuration was passed. The goal would be to, ideally, know directly in the IDE which parameters should be passed to the kernel for each module.

```
Core --> {
    autocomplete name of configuration keys.
}
```

**Comment by mathieugh** [comment]
Configuration issue was updated.
