### ISSUE TITLE
Create the tracing component

### ISSUE THREAD

**Issue by etiennenoel** [ima-tech/pristine-ts#7]
The tracing component must support easily adding traces to calculate how long operations too. 

We will need to support adapters to send the trace results to 3rd partys (AWS Lambda, Sentry, Datadog, etc.)

I wonder if we should use https://github.com/opentracing/opentracing-javascript/ @mathieugh @Maxime-Gosselin ? It has no dependencies and maybe we could wrap it?

**Comment by etiennenoel** [comment]
We should probably create network interceptors and everything so that when you include this module, it comes builtin with everything setup. WE should probably have a way to activate or deactivate tracing on top of that.

**Comment by Maxime-Gosselin** [comment]
I mean, we could. It seems that their goal is to standardize tracing for distributed application. It perfectly aligned with our goal here. Plus it doesn't seem complicated to use.

I am not sure I understand the goal of the network layer. Would all of our tracing pass through that layer and depending on what is configure (AWS Lambda / Xray, Sentry, Datadog) it would then get dispatch to their respective service ? Or this mechanism would be the adapters ? Or am I confusing two different thing ?

**Comment by etiennenoel** [comment]
Yes, something like that. I think we can approach tracing in a similar manner we approached logging. We want to be able to send the trace to different services. It would be nice for it to be plug and play, meaning you include the tracing module and you are good to go.

**Comment by etiennenoel** [comment]
I just read that OpenTracing is now becoming OpenTelemetry. https://opentelemetry.io/docs/js/getting_started/nodejs/

They are combining Tracing with Metrics to provide a global solution under the name Telemetry.

What's interesting, is that it makes it easy for example to increment a number whenever there's a specific request. You can then out of the box calculate metrics on the number of http requests, the average response time, etc.. and then, when you need to investigate, you look at the traces.
